### ISSUE TITLE
Table and list generation not working

### ISSUE THREAD

**Issue by Frogli** [bheston/rivet-sketch-plugin#1]
Dear @bheston,

Thank you for making this plugin available. It looks very promising and could save a lot of time. I am trying to get this plugin to work, but I have some problems. I see the plugin in the menu Plugins. And I can set the options for the table and enter some 'fake' data. But after clicking the button **Generate** the table is not placed on the artboard. The same applies for the List option.

I use:
Sketch version 55.2 (78181)
MacOS 10.14.5
Rivet plugin: 1.0.0

**Steps to reproduce**
1. Install the plugin by downloading the package from the Release page of the this Github repository and unzip the zip file.
2. Double click the file rivet.sketchplugin
3. Open a new Sketch document
4. Add a artboard
5. Click 'Plugins > Rivet > Rivet table
6. Set some options and/or click Generate

**Result**
- No table is added. 
- I checked the sketch logs and saw the following:

```
2019-07-19T12:47:56.912Z Rivet Table - INFO: Context initialized
2019-07-19T12:47:58.519Z Rivet Table - DEBUG: rowCount - 10
2019-07-19T12:47:58.524Z Rivet Table - ERROR: *** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray
2019-07-19T12:47:58.547Z Rivet Table - INFO: Plugin run complete
```

**Comment by bheston** [comment]
Thanks for submitting the first issue! And the console logs and detailed steps. :) Looks like there might be something that changed in the latest version. I’ll take a look over the weekend. Usually pretty easy to fix.

**Comment by bheston** [comment]
My apologies, I realized I didn't reply to this. I was able to reproduce the issue on a blank document. The usage notes probably don't make this clear enough, but the plugin requires some template symbols to operate. Please open the `Rivet Template.sketch` file and start from there or copy the symbols into your document.

I'll add a check and warning for this case to make the messaging more clear.
